title: Conference Deadlines
description: Deadlines for conferences in AR/VR/CV/HCI.
author: Larina Wang

domain: "https://idmwy.github.io/conference-deadlines/"
baseurl: ""

#twitter_username: abhshkdz
#twitter_hashtag: machinelearning
github_username: idmwy
github_repo: conferences

markdown: kramdown


include: ['_pages']
